# Тема “Вычисления с помощью Numpy”

In [1]:
import numpy as np

# Задание 1

In [2]:
 a = np.array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [3]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [4]:
mean_a = np.mean(a,axis=0)

In [5]:
mean_a

array([2. , 8.4])

# Задание 2

In [6]:
a[:,0]-mean_a[0]

array([-1.,  0.,  1.,  1., -1.])

In [7]:
a_centered = np.column_stack((a[:,0] - mean_a[0], a[:,1] - mean_a[1]))

In [8]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

# Задание 3

In [9]:
a_centered_sp = np.dot(a_centered[:,0],a_centered[:,1])

In [10]:
a_centered_sp

8.0

In [11]:
result = a_centered_sp / (a_centered.shape[0]-1)

In [12]:
result

2.0

# Задание 4

In [13]:
c=a.transpose()

In [14]:
c

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [15]:
np.cov(c)

array([[1. , 2. ],
       [2. , 4.3]])